export const TOKEN_CONSTANTS = {
  ACCESS_TOKEN_EXPIRES_IN: '60m',
  REFRESH_TOKEN_EXPIRES_IN: '7d',
  ACCESS_TOKEN_DB_EXPIRATION: 60 * 60,
  REFRESH_TOKEN_DB_EXPIRATION: 7 * 24 * 60 * 60,
  REFRESH_TOKEN_COOKIE_MAX_AGE: 7 * 24 * 60 * 60 * 1000,
  MAX_ACTIVE_SESSIONS: 10,
} as const;
